development:
  stripe_publishable_key:  pk_test_51Jv4zxJQgdmGrgHzahGPyYeGx5nIMM06NzED9v4aAqCJG8Icd9Ft0iWbGkAQYGqLvYQhoVBa5yohccFPozo587O700B0pSdbaa
  stripe_secret_key:  sk_test_51Jv4zxJQgdmGrgHzPWK7Yjfx6jbkWZe52XNjChgnTs3vCCN4rolgh6yS4mA9DUf22lc8Dp7Ud0DmzHOLjqfdItBk00kjHIObJG
